apiVersion: v1
kind: Service
metadata:
  name: languages-app
  labels:
    app: languages-app
    service: languages-app
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "3000"
    prometheus.io/scrape: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 3000
  selector:
    app: languages-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: languages-app
  labels:
    app: languages-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: languages-app
  template:
    metadata:
      labels:
        app: languages-app
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
      - name: languages-app
        image: ghcr.io/alfiankan/majelis-it-ci-cd-kubernetes-playground:8f1e01b
        ports:
        - containerPort: 3000
        env:
          - name: JAEGER_COLLECTOR_HOST
            value: 'http://tempo.default.svc.cluster.local:14268'
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
