apiVersion: v1
kind: Service
metadata:
  name: game-app
  labels:
    app: game-app
    service: game-app
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5000"
    prometheus.io/scrape: "true"
spec:
  ports:
    - port: 80
      name: http
      targetPort: 5000
  selector:
    app: game-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-app
  labels:
    app: game-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-app
  template:
    metadata:
      labels:
        app: game-app
    spec:
      containers:
        - name: game-app
          image: majelis-aiti/game-app:v2.0.0
          env:
            - name: LANGUAGE_APP_HOST
              value: "http://languages-app.default.svc.cluster.local"
            - name: JAEGER_COLLECTOR_HOST
              value: 'http://tempo.default.svc.cluster.local:14268'
          ports:
            - containerPort: 5000

