kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOiB7CgkJCSJhdXRoIjogIlZWTkZVazVCVFVVNloyaDFYMGRaYW1WU1FsazFNVlYzUW5oUVprdElhRU4wYlhoelNtZHlOMGRwVkRFMk1HcERUQT09IgoJCX0sCgkJImdoY3IuaW8iOiB7CgkJCSJhdXRoIjogImRYTmxjbTVoYldVNloyaHdYMDlVYVVGUFlsaE9NbFIxTVRWcGVrVTFPRzFKZDJ4dVZFTTVabVZIWXpCaGQweEdOZz09IgoJCX0sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHsKCQkJImF1dGgiOiAiWTI5a1pYTndZV05sYzJSbGRqcGtaakJsWlRaaFpDMW1PV0l5TFRReU0yTXRPRGM0WmkwMk16VmtNR001TkdSall6ST0iCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiWC1NZXRhLVNvdXJjZS1DbGllbnQiOiAiZ2l0aHViL2NvZGVzcGFjZXMiCgl9Cn0=