name: CI & deploy to staging

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: unit testing
      run: cd languages-app &&  go test -v -timeout=0

  build_push:
    name: Build & Push Image
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: USERNAME
        password: ${{ secrets.GITUB_PAT }}

    - name: Inject version
      run: echo "ENV APP_VERSION=$SHORT_SHA" >> languages-app/Dockerfile

    - name: Build & Push
      env:
        SHORT_SHA: main
      run: |
        SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")
        docker build -t ghcr.io/alfiankan/${{ github.event.repository.name }}:$SHORT_SHA ./languages-app
        docker push ghcr.io/alfiankan/${{ github.event.repository.name }}:$SHORT_SHA
