name: CI & deploy to staging

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: chdir to project
      run: cd languages-app
    - name: unit testing
      run: JAEGER_COLLECTOR_HOST=http://fake-tracer.local &&  go test -v -timeout=0

  build_push:
    name: Build & Push Image
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: USERNAME
        password: ${{ secrets.GITUB_PAT }}

    - name: inject version
      run: echo "ENV APP_VERSION=$(git rev-parse --short "$GITHUB_SHA")" >> languages-app/Dockerfile

    - name: Build & Push
      run: |
        docker build -t ghcr.io/alfiandra/${{ github.event.repository.name }}:main ./languages-app
        docker push ghcr.io/alfiandra/${{ github.event.repository.name }}:$(git rev-parse --short "$GITHUB_SHA")
