name: Roolback Production

on:
  workflow_dispatch:

jobs:
  rollback:
    name: Rollback Production
    runs-on: ubuntu-latest
    steps:
    - name: update deployment
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.21.0
        command: -n production rollout undo deployment/languages-app
